### ISSUE TITLE
eval.jax の未訳文を翻訳する

### ISSUE THREAD

**Issue by koron** [vim-jp/vimdoc-ja-working#48]
from #41, related: #27

---

残件一覧

Chapter 1-3:
- [x] non-zero-arg (@kashewnuts, #84)
- [x] v:mouse_winid (@crazymaster, #82)

Chapter 4:
- [x] functions (関数リスト) (@kashewnuts)
- [x] assert_inrange (@kashewnuts, #87)
- [x] assert_match (@kashewnuts, #87)
- [x] assert_notequal (@kashewnuts, #87)
- [x] assert_notmatch (@kashewnuts, #87)
- [x] bufwinid (@kashewnuts, #96)
- [x] ch_close (@mattn, #93)
- [x] ch_close_in (@mattn, #93)
- [x] ch_evalexpr (@mattn, #93)
- [x] ch_evalraw (@mattn, #93)
- [x] ch_getbufnr (@mattn, #93)
- [x] ch_getjob (@mattn, #93)
- [x] ch_info (@mattn, #93)
- [x] ch_log (@mattn, #93)
- [x] ch_logfile (@mattn, #93)
- [x] ch_open (@mattn, #93)
- [x] ch_read (@mattn, #93)
- [x] ch_readraw (@mattn, #93)
- [x] ch_sendexpr (@mattn, #93)
- [x] ch_sendraw (@mattn, #93)
- [x] ch_setoptions (@mattn, #93)
- [x] ch_status (@mattn, #93)
- [x] execute (@yassu, #94)
- [x] feedkeys (@yassu, #100)
- [x] funcref (@yassu, #101)
- [x] function (@yassu, #102)
- [x] garbagecollect (@kashewnuts, #96)
- [x] get (@kashewnuts, #96)
- [x] getbufinfo (@kashewnuts, #96)
- [x] getbufvar (@kashewnuts, #96)
- [x] getcompletion (@kashewnuts, #96)
- [x] getloclist (@kashewnuts, #96)
- [x] getqflist (@kashewnuts, #96)
- [x] gettabinfo (@kashewnuts, #96)
- [x] getwininfo (@kashewnuts, #96)
- [x] glob2regpat (@kashewnuts, #96)
- [x] job_getchannel (@kashewnuts, #92)
- [x] job_info (@kashewnuts, #92)
- [x] job_setoptions (@kashewnuts, #92)
- [x] job_start (@kashewnuts, #92)
- [x] job_status (@kashewnuts, #92)
- [x] job_stop (@kashewnuts, #92)
- [x] js_decode (@mattn, #95)
- [x] js_encode (@mattn, #95)
- [x] matchstrpos (@mattn, #95)
- [x] printf (@mattn, #95)
- [x] reltimefloat (@mattn, #95)
- [x] screenrow (@mattn, #95)
- [x] setfperm (@mattn, #95)
- [x] setloclist (@mattn, #95)
- [x] setqflist (@mattn, #95)
- [x] strcharpart (@mattn, #95)
- [x] strgetchar (@mattn, #95)
- [x] substitute (@mattn, #95)
- [x] test_alloc_fail (@aiya000, #86)
- [x] test_autochdir (@aiya000, #86)
- [x] test_disable_char_avail (@aiya000, #86)
- [x] test_garbagecollect_now (@aiya000, #86)
- [x] test_null_channel (@aiya000, #86)
- [x] test_null_dict (@aiya000, #86)
- [x] test_null_job (@aiya000, #86)
- [x] test_null_list (@aiya000, #86)
- [x] test_null_partial (@aiya000, #86)
- [x] test_null_string (@aiya000, #86)
- [x] test_settime (@aiya000, #86)
- [x] timer_info (@mattn, #91)
- [x] timer_pause (@mattn, #91)
- [x] timer_start (@mattn, #91)
- [x] timer_stop (@mattn, #91)
- [x] timer_stopall (@mattn, #91)
- [x] win_findbuf (@mattn, #91)
- [x] win_getid (@mattn, #91)
- [x] win_gotoid (@mattn, #91)
- [x] win_id2tabwin (@mattn, #91)
- [x] win_id2win (@mattn, #91)
- [x] winwidth (@kashewnuts, #96)
- [x] feature-list (@kashewnuts, #96)

Chapter 13:
- [x] Testing (@kashewnuts, #84)

---

You can check differences at local with this command:

```
git show 24fd5e10 -- en/{FILENAME}.txt
```

**Comment by mattn** [comment]
何が残でしょうか。

**Comment by k-takata** [comment]
一番上のリストに挙がっている項目の翻訳全部です。英文の差分反映だけは終わっています。

**Comment by mattn** [comment]
こちの翻訳も立候補者は宣言をお忘れなく。
あとバッティング/コンフリクトを避けるために小まめにマージしながらやります？

**Comment by aiya000** [comment]
- test_alloc_fail
- test_autochdir
- test_disable_char_avail
- test_garbagecollect_now
- test_null_channel
- test_null_dict
- test_null_job
- test_null_list
- test_null_partial
- test_null_string
- test_settime

練習がてら、これらの翻訳を行ってもいいですか？

**Comment by kashewnuts** [comment]
@aiya000 ↑で割り当てておきました 👍

**Comment by mattn** [comment]
ch_canread も追加される予定です。

**Comment by aiya000** [comment]
終わったので、[こちらのPR](https://github.com/vim-jp/vimdoc-ja-working/pull/86)に投げておきました！  
test_garbagecollect_nowの翻訳を意訳するか、直訳するか迷いましたが、間違ってたら事なので直訳しましたw

**Comment by mattn** [comment]
だんだん終わりが見えてきたぞー！

**Comment by yassu** [comment]
* execute
* feedkeys
* funcref
* function

これらの翻訳をやってみて良いでしょうか?

**Comment by mattn** [comment]
だいぶ減ってきたぞ

**Comment by k-takata** [comment]
ちなみに、これが終われば、最新の 8.0.0160 との差分があとこのくらい。

```
 en/eval.txt    | 119 +++++++++++++++++++++++++++++++++++++++------------------
 en/intro.txt   |  14 ++++---
 en/message.txt |   7 ++--
 en/scroll.txt  |   5 ++-
 en/usr_41.txt  |   3 +-
 en/windows.txt |   4 +-
 6 files changed, 102 insertions(+), 50 deletions(-)
```

元々差分はもっとありましたが、master に直接修正をつっこんじゃいました。

**Comment by kashewnuts** [comment]
あともう少し！！

**Comment by k-takata** [comment]
あとは、関数リストと @yassu さん担当分が完了すれば、8.0.0168 までの追従がすべて完了のはずです。

**Comment by yassu** [comment]
ごめんなさいごめんなさい.
土日で一気にやります.

**Comment by kashewnuts** [comment]
@yassu 時間がかかりそうとか、○日までは手が出せなくなったとかありましたら、
その旨伝えていただければ大丈夫ですよー。

そういえばfunctions (関数リスト) の翻訳をしたいと思うのですが、
2023行目付近の`execute()`と2053行目付近の`funcref()`は担当していただけるという認識でよろしいですか？

**Comment by yassu** [comment]
はい. その認識です.

**Comment by kashewnuts** [comment]
@yassu 承知しました。それではよろしくお願いします。

**Comment by k-takata** [comment]
`getbufvar`, `json_encode` に未翻訳部分を発見。

**Comment by mattn** [comment]
お、僕の可能性...

**Comment by k-takata** [comment]
`v:hlsearch` も。リスト作成時の漏れの可能性。

**Comment by kashewnuts** [comment]
`getbufvar`は自分の翻訳漏れですね…
`json_encode`と`v:hlsearch`もついでにやっときます。

**Comment by mattn** [comment]
終わったでー！皆さんお疲れさまでした！

**Comment by koron** [comment]
おつかれさまでした&ありがとうございました! (｀･ω･´)ゞ

**Comment by aiya000** [comment]
:dango: :joy_cat:  :cheese:

**Comment by kashewnuts** [comment]
わーい！！！やっと終わったぞー 😆 
お疲れ様でした&ありがとうございました！
